blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^catalog/(?P<id>[0-9]+)$', views.catalog, name='catalog'),
    url(r'^info/(?P<id>[0-9]+)$', views.info, name='info'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from Tkconstants import CASCADE

from django.db import models

from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager, PermissionsMixin)
from django.contrib.auth.models import User
# Create your models here.


# class Account(models.Model):
#     user          = models.OneToOneField(User, on_delete=models.CASCADE)
#     name          = models.CharField(max_length=120, null=True)
#     nickname          = models.CharField(max_length=200, null=True)
#     id_face       = models.CharField(max_length=100, null=True)
#     url_face      = models.CharField(max_length=300, null=True)
#     sex           = models.CharField(max_length=50, null=True)
#     image         = models.CharField(max_length=500, null=True)
#     birtday       = models.DateField()
#     religion      = models.CharField(max_length=200, null=True)
#     location      = models.CharField(max_length=200, null=True)
#     CHOICE_STATUS = (('1', 'Single'),('2', 'Married'),('3', 'Divorce'))
#     status        = models.CharField(choices=CHOICE_STATUS, max_length=1, default= 1)  
#     work          = models.CharField(max_length=200, null=True)
#     likes         = models.CharField(max_length=200, null=True)
#     dislikes      = models.CharField(max_length=200, null=True)
#     hobbies       = models.CharField(max_length=500, null=True)
#     favorite_food = models.CharField(max_length=200, null=True)
#     favorite_drink= models.CharField(max_length=200, null=True)
#     motto_in_life = models.CharField(max_length=500, null=True)
#     CHOICE_TYPE   = (('1', 'Admin'),('2', 'Manager'),('3', 'Author'),('4', 'Member'))
#     type_account  = models.CharField(choices=CHOICE_TYPE, max_length=1, default= 4)
#     date_register = models.DateTimeField(auto_now_add=True)
#     CHOICE_ACTION = (('1', 'True'),('0', 'False'))
#     active        = models.CharField(choices=CHOICE_ACTION, max_length=1, default=0)
#     def __str__(self):
#         return self.name

class Catalog(models.Model):
    name            = models.CharField(max_length=100)
    unsigned_name   = models.CharField(max_length=200)
    order_sort      = models.IntegerField()
    CHOICE_PUBLIC   = (('1', 'True'), ('0', 'False'))
    public          = models.CharField(default=0, max_length=1, choices=CHOICE_PUBLIC)
    meta_desc       = models.CharField(max_length=120)
    meta_key        = models.CharField(max_length=120)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name            = models.CharField(max_length=200)
    unsigned_name   = models.CharField(max_length=200)
    created         = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name


class Posts(models.Model):
    title               = models.CharField(max_length=200)
    unsigned_title      = models.CharField(max_length=250)
    excerpt             = models.TextField()
    image               = models.ImageField(upload_to='posts/')
    date                = models.DateTimeField(auto_now_add=True)
    author                = models.OneToOneField(User, on_delete=models.CASCADE)
    content             = models.TextField()
    id_catalog          = models.ForeignKey(Catalog, on_delete=models.CASCADE, verbose_name='Catalog')
    view                = models.IntegerField(default=0, verbose_name ='View')
    tag                 = models.ManyToManyField(Tag, related_name='posts')
    CHOICE_HIGHLIGHT    = (('1', 'True'), ('0', 'False'))
    highlight           = models.CharField(default=0, max_length=1, choices=CHOICE_HIGHLIGHT)
    CHOICE_PUBLIC       = (('1', 'Public'), ('0', 'Private'))
    public              = models.CharField(default=1, max_length=1, choices=CHOICE_PUBLIC)
    show_group          = models.IntegerField(default=0)
    def __str__(self):
        return self.title


class Comment(models.Model):
    user            = models.OneToOneField(User, on_delete=models.CASCADE)
    content         = models.TextField()
    date            = models.DateTimeField(auto_now_add=True)
    id_post         = models.ForeignKey(Posts, on_delete=models.CASCADE, verbose_name='Post')
    CHOICE_PUBLIC   = (('1','True'),('0', 'False'))
    public          = models.FileField(default=1, choices=CHOICE_PUBLIC, max_length=1)

    def __str__(self):
        return self.content


class Setup(models.Model):
    name = models.CharField(max_length=250)
    description = models.CharField(max_length=250)
    about = models.CharField(max_length=250)
    image = models.ImageField(upload_to='avatar/')

class Online(models.Model):
    ip = models.GenericIPAddressField()
    created = models.DateTimeField(auto_now_add=True)

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
from .models import Posts, Catalog, Comment, Setup

from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger


from django.shortcuts import redirect

from django.utils import timezone

from django.http import HttpResponse



    
def index(request):
    new_post = Posts.objects.all().order_by('date').filter(public=1)[0:5]
    list_post = Posts.objects.all().order_by('view').filter(public=1)[0:5]
    list_important = Posts.objects.all().order_by('view').filter(public=1, highlight=1)[0:5]
    list_catalog = Catalog.objects.all()
    setup = Setup.objects.all()[0:1]

    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        print ("returning FORWARDED_FOR")
        ip = x_forwarded_for.split(',')[-1].strip()
    elif request.META.get('HTTP_X_REAL_IP'):
        print ("returning REAL_IP")
        ip = request.META.get('HTTP_X_REAL_IP')
    else:
        print ("returning REMOTE_ADDR")
        ip = request.META.get('REMOTE_ADDR')

    return render(
        request,
        'blog/index.html',
        {
            'list_post': list_post,
            'new_post': new_post,
            'list_catalog': list_catalog,
            'list_important': list_important,
            'your_ip': ip,
            'setup': setup,
        }
    )

def catalog(request, id):
    check_catalog = Catalog.objects.get(id=id)
    list_post_catalog = Posts.objects.all().order_by('-date').filter(public=1, id_catalog=id)
    result = list_post_catalog.count()
    list_catalog = Catalog.objects.all()
    setup = Setup.objects.all()[0:1]

    paginator = Paginator(list_post_catalog, 5)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)


    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        print ("returning FORWARDED_FOR")
        ip = x_forwarded_for.split(',')[-1].strip()
    elif request.META.get('HTTP_X_REAL_IP'):
        print ("returning REAL_IP")
        ip = request.META.get('HTTP_X_REAL_IP')
    else:
        print ("returning REMOTE_ADDR")
        ip = request.META.get('REMOTE_ADDR')


    return  render(
        request,
        'blog/catalog.html',
        {
            'check_catalog': check_catalog,
            'result' : result,
            'list_catalog': list_catalog,
            'posts' : posts,
            'your_ip': ip,
            'setup': setup,
        }
    )



def update_view_post(id):
    post = Posts.objects.get(id=id)
    post.view = post.view + 1
    post.save()



def info(request, id):

    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        website = request.POST.get('website')
        content = request.POST.get('content')
        post = Posts.objects.get(pk=id)
        post.comment_set.create(
            name = name,
            email = email,
            website = website,
            content = content,
            image = '',
            public = '1'
        )
        return redirect('/info/'+id)
    setup = Setup.objects.all()[0:1]
    list_comment = Comment.objects.all().order_by('date').filter(id_post_id=id)
    post_info = Posts.objects.filter(id=id).first()
    list_catalog = Catalog.objects.all()
    update_view_post(id)
    list_tag = post_info.tag.all()


    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        print ("returning FORWARDED_FOR")
        ip = x_forwarded_for.split(',')[-1].strip()
    elif request.META.get('HTTP_X_REAL_IP'):
        print ("returning REAL_IP")
        ip = request.META.get('HTTP_X_REAL_IP')
    else:
        print ("returning REMOTE_ADDR")
        ip = request.META.get('REMOTE_ADDR')

    return render(
        request,
        'blog/info.html',
        {
            'list_comment': list_comment,
            'post_info': post_info,
            'list_catalog': list_catalog,
            'list_tag': list_tag,
            'your_ip': ip,
            'setup': setup,
        }
    )

blog/templates/blocks/about.html
<section class="about section">
    <div class="section-inner">
        <h2 class="heading">About Group</h2>
        <div class="content">
            <p>Write a brief intro about yourself. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec.</p>    

            <p>It's a good idea to include your personal interests and hobbies as well. Commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec.Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
            
        </div><!--//content-->
    </div><!--//section-inner-->                 
</section><!--//section-->

blog/templates/blocks/catalog.html
{% if check_catalog %}
<section class="latest section">
    <div class="section-inner">
        <h2 class="heading">Have {{ result }} result for catalog: "{{ check_catalog.name }}"</h2>
        <div class="content">
            {% for item in posts %}
            <div class="item row">
                <a class="col-md-4 col-sm-4 col-xs-12" href="{% url 'blog:info' item.id %}  " >
                <img class="img-responsive project-image" src="/media/{{ item.image }}" alt="{{ item.unsigned_title }}" />
                </a>

                <div class="desc col-md-8 col-sm-8 col-xs-12">
                    <h3 class="title"><a href="{% url 'blog:info' item.id %}" >{{ item.title }}</a></h3>
                    <p>{{ item.excerpt }}</p>
                    <p><a class="more-link" href="{% url 'blog:info' item.id %}" ><i class="fa fa-external-link"></i> More Info</a></p>
                </div><!--//desc-->
            </div><!--//item-->
            {% endfor %}
        </div><!--//content-->
    </div><!--//section-inner-->
</section><!--//section-->
{% else %}
    {% include 'blocks/404.html' %}
{% endif %}

blog/templates/blocks/comment.html
{% if post_info and post_info.public == '1' %}
<section class="github section">
    <div id="comments">
        <h2>Comments</h2>
        <ul>
            {% if list_comment %}
            {% for item in list_comment %}
            <li>
                <article>
                    <header>
                          <figure class="avatar"><img src="/static/images/user.png" alt="" class="" style="width:20px;"></figure>
                          <address>
                          <a href="">{{ item.name }}</a> say:
                          </address>
                          <time></time>
                    </header>
                    <div class="comcont">
                        <p>{{ item.content }}</p>
                    </div>
                </article>
            </li>
            {% endfor %}
            {% else %}
			<li>
                <article>
                    <div class="comcont">
                        <p class="text-center">You are first comment for comment this post</p>
                    </div>
                </article>
			</li>
            {% endif %}
        </ul>

        <h2>Write A Comment</h2>
        <form method="post" action="{% url 'blog:info' post_info.id %}">
            {% csrf_token %}
            <div class="one_third first">
                <label for="name">Name <span>*</span></label>
                <input type="text" name="name" id="name" value="" size="22" required>
            </div>
            <div class="one_third">
                <label for="email">Mail <span>*</span></label>
                <input type="email" name="email" id="email" value="" size="22" required>
            </div>
            <div class="one_third">
                <label for="url">Website</label>
                <input type="url" name="website" id="url" value="" size="22">
            </div>
            <div class="block clear">
                <label for="comment">Your Comment</label>
                <textarea name="content" id="comment" cols="25" rows="10"></textarea>
            </div>
            <div>
                <input type="submit" name="add_comment" value="Submit Form">
              &nbsp;
                <input type="reset" name="reset" value="Reset Form">
            </div>
        </form>
    </div>
</section><!--//section-->
{% endif %}

blog/templates/blocks/content.html
<section class="about section">
	<div class="section-inner">
	    <h2 class="heading">About Me</h2>
	    <div class="content">
	        <p>Write a brief intro about yourself. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec.</p>    

			<p>It's a good idea to include your personal interests and hobbies as well. Commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec.Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
	     
	    </div><!--//content-->
	</div><!--//section-inner-->                 
</section><!--//section-->

blog/templates/blocks/content2.html
{% if post_info and post_info.public == '1' %}
<section class="latest section">
    <div class="section-inner">
        <div class="item featured text-center">
            <h2 class="heading"><a href="#" target="_blank">{{ post_info.title }}</a></h3></h2>
            <p class="summary">{{ post_info.excerpt }}</p>
            <div class="featured-image">
                <a href="#" target="_blank">
                <img class="img-responsive img-thumbnail project-image border" style="width: 100%"  src="/media/{{ post_info.image }}" alt="project name" />
                </a>
                <div class="ribbon">
                    <div class="text">New</div>
               	</div>

            </div>
                
            <div class="desc text-left">                                    
                <!-- content -->
				{{ post_info.content }}
            </div><!--//desc-->

            <div class="form-inline">
                <p><b class="fa fa-calendar pull-left" > {{ post_info.date }}</b> <b class="fa fa-user pull-right"> {{ post_info.author}}</b></p>
            </div>
            <hr>
            <div class="form-inline">
                <p>
                    <b class="fa fa-tag pull-left" > Tag: </b>
                    <span class="pull-left">
                        {% for tag in list_tag %}
                            <a href="#">{{ tag.name }}</a> ,
                        {% endfor %}
                    </span>
                </p>
            </div>
        </div><!--//item-->
    </div>
</section>
{% else %}
    {% include 'blocks/404.html' %}
{% endif %}

blog/templates/blocks/footer.html
<footer class="footer">
    <div class="container text-center">
            <small class="copyright">Designed with <i class="fa fa-heart"></i> by <a href="/" target="_blank">Write Code To Life</a> for developers</small>
    </div><!--//container-->
</footer><!--//footer-->

blog/templates/blocks/head.html
    {% load static %}
    <title>Teletubbies Active 24°🌠</title>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Responsive HTML5 Website landing Page for Developers">
    <meta name="author" content="3rd Wave Media">
    <link rel="shortcut icon" href="favicon.ico">
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,300italic,400italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <!-- Global CSS -->
    <link rel="stylesheet" href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}">
    <!-- Plugins CSS -->
    <link rel="stylesheet" href="{% static 'assets/plugins/font-awesome/css/font-awesome.css' %}">
    <!-- github acitivity css -->
    <link rel="stylesheet" href="{% static 'assets/plugins/github-activity/dist/github-activity-0.1.1.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/plugins/github-activity/dist/octicons/octicons.min.css' %}">
    <link href="{% static 'layout/styles/layout.css' %}" rel="stylesheet" type="text/css" media="all">
    <link href="{% static 'layout/styles/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all">

    <!-- Theme CSS -->
    <link id="theme-style" rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script type="text/javascript" src="{% static 'assets/plugins/jquery-1.11.2.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/plugins/jquery-migrate-1.2.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <!--<script type="text/javascript" src="{% static 'assets/plugins/jquery-rss/dist/jquery.rss.min.js' %}"></script>-->
    <!-- github activity plugin -->
    <script type="text/javascript" src="{% static 'assets/plugins/github-activity/dist/mustache/mustache.min.js' %}"></script>
    <!--<script type="text/javascript" src="{% static 'assets/plugins/github-activity/dist/github-activity-0.1.1.min.js' %}"></script>-->
    <!-- custom js -->
    <!--<script type="text/javascript" src="{% static 'assets/js/main.js' %}"></script>-->

blog/templates/blocks/header.html
<header class="header">
    <div class="container">
        <div class="profile-content pull-left">
            <img class="profile-image img-circle pull-left" src="https://scontent.fsgn4-1.fna.fbcdn.net/v/t34.0-12/26551555_1676701442372758_1279523686_n.jpg?_nc_cat=0&oh=bff4bc8d2b6ef4211bcd6d36038bc9e5&oe=5AD0CECD" alt="Teletubbies Active 24" />
            <h1 class="name"style ="font-size: 52px;" ><a href="/">Teletubbies Active 24°🌠</a></h1>
            <h2 class="desc">make friends international</h2>   
        </div><!--//profile-->
                  
    </div><!--//container-->
</header><!--//header-->

blog/templates/blocks/header_post.html
<header class="header">
    <div class="container">                       
        <img class="profile-image img-responsive pull-left img-circle " style="width:180px; height:180px;" src="admin/<?php echo $info_user['avatar']; ?>" alt="<?php echo $info_user['name']; ?>" />
        <div class="profile-content pull-left">
            <h1 class="name">< echo $info_user['name']></h1>
            <h2 class="desc">< nn ></h2>
            <ul class="social list-inline">
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>                   
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                <li><a href="#"><i class="fa fa-github-alt"></i></a></li>                  
                <li class="last-item"><a href="#"><i class="fa fa-hacker-news"></i></a></li>                 
            </ul> 
        </div><!--//profile-->
        <a class="btn btn-cta-primary pull-right" href="#" target="_blank"><i class="fa fa-paper-plane"></i> Contact Me</a>              
    </div><!--//container-->
</header><!--//header-->

blog/templates/blocks/home.html
<?php 
	include 'list_post.php';
	include 'list_post2.php';
	include 'list_post3.php';
?>

blog/templates/blocks/list_post2.html
<section class="projects section">
    <div class="section-inner">
        <h2 class="heading"><span style="color: #FFA500;">Post Popular</span></h2>
        <div class="content">
            {% if list_post %}
            {% for item in list_post %}
            <div class="item">
                <h3 class="title"><a href="{% url 'blog:info' item.id %}">{{ item.title }}</a></h3>
                <p class="summary">{{ item.excerpt }}</p>
                <p><a class="more-link" href="{% url 'blog:info' item.id %}" target="_blank"><i class="fa fa-external-link"></i>More Info</a></p>
            </div><!--//item-->
            {% endfor %}
            {% endif %}
        </div><!--//content-->  
    </div><!--//section-inner-->                 
</section><!--//section-->

blog/templates/blocks/list_post3.html
<section class="experience section">
    <div class="section-inner">
        <h2 class="heading"><span style="color:green;">Improtant Post</span></h2>
        <div class="content">
            {% for item in list_important %}
            <div class="item">
                <h3 class="title"><a href="{% url 'blog:info' item.id %}">{{ item.title }}</a></h3>
                <p>{{ item.excerpt }}</p>
            </div><!--//item-->
            {% endfor %}
        </div><!--//content-->  
    </div><!--//section-inner-->                 
</section><!--//section-->

blog/templates/blocks/more.html
<a class="btn btn-cta-secondary" href="#">More CoderWall <i class="fa fa-chevron-right"></i></a>

blog/templates/blocks/pagination.html

<div class="section-inner">
	{% if posts.has_next %}
	<a class="btn btn-cta-secondary" style="" href="?page={{ posts.next_page_number }}"><i class="fa fa-chevron-left"></i>Prew</a>
	{% endif %}
	{% if posts.has_previous %}
	<a class="btn btn-cta-secondary" style="" href="?page={{ posts.previous_page_number }}">Next <i class="fa fa-chevron-right"></i></a>
	{% endif %}
</div>