blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^catalog/(?P<id>[0-9]+)$', views.catalog, name='catalog'),
    url(r'^info/(?P<id>[0-9]+)$', views.info, name='info'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from Tkconstants import CASCADE

from django.db import models

from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager, PermissionsMixin)
from django.contrib.auth.models import User
# Create your models here.


# class Account(models.Model):
#     user          = models.OneToOneField(User, on_delete=models.CASCADE)
#     name          = models.CharField(max_length=120, null=True)
#     nickname          = models.CharField(max_length=200, null=True)
#     id_face       = models.CharField(max_length=100, null=True)
#     url_face      = models.CharField(max_length=300, null=True)
#     sex           = models.CharField(max_length=50, null=True)
#     image         = models.CharField(max_length=500, null=True)
#     birtday       = models.DateField()
#     religion      = models.CharField(max_length=200, null=True)
#     location      = models.CharField(max_length=200, null=True)
#     CHOICE_STATUS = (('1', 'Single'),('2', 'Married'),('3', 'Divorce'))
#     status        = models.CharField(choices=CHOICE_STATUS, max_length=1, default= 1)  
#     work          = models.CharField(max_length=200, null=True)
#     likes         = models.CharField(max_length=200, null=True)
#     dislikes      = models.CharField(max_length=200, null=True)
#     hobbies       = models.CharField(max_length=500, null=True)
#     favorite_food = models.CharField(max_length=200, null=True)
#     favorite_drink= models.CharField(max_length=200, null=True)
#     motto_in_life = models.CharField(max_length=500, null=True)
#     CHOICE_TYPE   = (('1', 'Admin'),('2', 'Manager'),('3', 'Author'),('4', 'Member'))
#     type_account  = models.CharField(choices=CHOICE_TYPE, max_length=1, default= 4)
#     date_register = models.DateTimeField(auto_now_add=True)
#     CHOICE_ACTION = (('1', 'True'),('0', 'False'))
#     active        = models.CharField(choices=CHOICE_ACTION, max_length=1, default=0)
#     def __str__(self):
#         return self.name

class Catalog(models.Model):
    name            = models.CharField(max_length=100)
    unsigned_name   = models.CharField(max_length=200)
    order_sort      = models.IntegerField()
    CHOICE_PUBLIC   = (('1', 'True'), ('0', 'False'))
    public          = models.CharField(default=0, max_length=1, choices=CHOICE_PUBLIC)
    meta_desc       = models.CharField(max_length=120)
    meta_key        = models.CharField(max_length=120)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name            = models.CharField(max_length=200)
    unsigned_name   = models.CharField(max_length=200)
    created         = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name


class Posts(models.Model):
    title               = models.CharField(max_length=200)
    unsigned_title      = models.CharField(max_length=250)
    excerpt             = models.TextField()
    image               = models.ImageField(upload_to='posts/')
    date                = models.DateTimeField(auto_now_add=True)
    author                = models.OneToOneField(User, on_delete=models.CASCADE)
    content             = models.TextField()
    id_catalog          = models.ForeignKey(Catalog, on_delete=models.CASCADE, verbose_name='Catalog')
    view                = models.IntegerField(default=0, verbose_name ='View')
    tag                 = models.ManyToManyField(Tag, related_name='posts')
    CHOICE_HIGHLIGHT    = (('1', 'True'), ('0', 'False'))
    highlight           = models.CharField(default=0, max_length=1, choices=CHOICE_HIGHLIGHT)
    CHOICE_PUBLIC       = (('1', 'Public'), ('0', 'Private'))
    public              = models.CharField(default=1, max_length=1, choices=CHOICE_PUBLIC)
    show_group          = models.IntegerField(default=0)
    def __str__(self):
        return self.title


class Comment(models.Model):
    user            = models.OneToOneField(User, on_delete=models.CASCADE)
    content         = models.TextField()
    date            = models.DateTimeField(auto_now_add=True)
    id_post         = models.ForeignKey(Posts, on_delete=models.CASCADE, verbose_name='Post')
    CHOICE_PUBLIC   = (('1','True'),('0', 'False'))
    public          = models.FileField(default=1, choices=CHOICE_PUBLIC, max_length=1)

    def __str__(self):
        return self.content


class Setup(models.Model):
    name = models.CharField(max_length=250)
    description = models.CharField(max_length=250)
    about = models.CharField(max_length=250)
    image = models.ImageField(upload_to='avatar/')

class Online(models.Model):
    ip = models.GenericIPAddressField()
    created = models.DateTimeField(auto_now_add=True)

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
from .models import Posts, Catalog, Comment, Setup

from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger


from django.shortcuts import redirect

from django.utils import timezone

from django.http import HttpResponse



    
def index(request):
    new_post = Posts.objects.all().order_by('date').filter(public=1)[0:5]
    list_post = Posts.objects.all().order_by('view').filter(public=1)[0:5]
    list_important = Posts.objects.all().order_by('view').filter(public=1, highlight=1)[0:5]
    list_catalog = Catalog.objects.all()
    setup = Setup.objects.all()[0:1]

    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        print ("returning FORWARDED_FOR")
        ip = x_forwarded_for.split(',')[-1].strip()
    elif request.META.get('HTTP_X_REAL_IP'):
        print ("returning REAL_IP")
        ip = request.META.get('HTTP_X_REAL_IP')
    else:
        print ("returning REMOTE_ADDR")
        ip = request.META.get('REMOTE_ADDR')

    return render(
        request,
        'blog/index.html',
        {
            'list_post': list_post,
            'new_post': new_post,
            'list_catalog': list_catalog,
            'list_important': list_important,
            'your_ip': ip,
            'setup': setup,
        }
    )

def catalog(request, id):
    check_catalog = Catalog.objects.get(id=id)
    list_post_catalog = Posts.objects.all().order_by('-date').filter(public=1, id_catalog=id)
    result = list_post_catalog.count()
    list_catalog = Catalog.objects.all()
    setup = Setup.objects.all()[0:1]

    paginator = Paginator(list_post_catalog, 5)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)


    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        print ("returning FORWARDED_FOR")
        ip = x_forwarded_for.split(',')[-1].strip()
    elif request.META.get('HTTP_X_REAL_IP'):
        print ("returning REAL_IP")
        ip = request.META.get('HTTP_X_REAL_IP')
    else:
        print ("returning REMOTE_ADDR")
        ip = request.META.get('REMOTE_ADDR')


    return  render(
        request,
        'blog/catalog.html',
        {
            'check_catalog': check_catalog,
            'result' : result,
            'list_catalog': list_catalog,
            'posts' : posts,
            'your_ip': ip,
            'setup': setup,
        }
    )



def update_view_post(id):
    post = Posts.objects.get(id=id)
    post.view = post.view + 1
    post.save()



def info(request, id):

    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        website = request.POST.get('website')
        content = request.POST.get('content')
        post = Posts.objects.get(pk=id)
        post.comment_set.create(
            name = name,
            email = email,
            website = website,
            content = content,
            image = '',
            public = '1'
        )
        return redirect('/info/'+id)
    setup = Setup.objects.all()[0:1]
    list_comment = Comment.objects.all().order_by('date').filter(id_post_id=id)
    post_info = Posts.objects.filter(id=id).first()
    list_catalog = Catalog.objects.all()
    update_view_post(id)
    list_tag = post_info.tag.all()


    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        print ("returning FORWARDED_FOR")
        ip = x_forwarded_for.split(',')[-1].strip()
    elif request.META.get('HTTP_X_REAL_IP'):
        print ("returning REAL_IP")
        ip = request.META.get('HTTP_X_REAL_IP')
    else:
        print ("returning REMOTE_ADDR")
        ip = request.META.get('REMOTE_ADDR')

    return render(
        request,
        'blog/info.html',
        {
            'list_comment': list_comment,
            'post_info': post_info,
            'list_catalog': list_catalog,
            'list_tag': list_tag,
            'your_ip': ip,
            'setup': setup,
        }
    )

blog/templates/blocks/widget/widget1.html
<aside class="info aside section">
    <div class="section-inner">
        <h2 class="heading sr-only">Basic Information</h2>
        <div class="content">
            <ul class="list-unstyled">
                <li><i class="fa fa-map-marker"></i><span class="sr-only">Your IP:</span>{{ your_ip }}</li>
            </ul>
        </div><!--//content-->  
    </div><!--//section-inner-->                 
</aside>

blog/templates/blocks/widget/widget2.html
<aside class="skills aside section">
    <div class="section-inner">
        <h2 class="heading">Skills</h2>
        <div class="content">
            <p class="intro">
                Intro about your skills goes here. Keep the list lean and only show your primary skillset. You can always provide a link to your Linkedin or Coderwall profile so people can get more info there.</p>
            
            <div class="skillset">
               
                <div class="item">
                    <h3 class="level-title">Python &amp; Django<span class="level-label" data-toggle="tooltip" data-placement="left" data-animation="true" title="You can use the tooltip to add more info...">Expert</span></h3>
                    <div class="level-bar">
                        <div class="level-bar-inner" data-level="96%">
                        </div>                                      
                    </div><!--//level-bar-->                                 
                </div><!--//item-->
                
                <div class="item">
                    <h3 class="level-title">Javascript &amp; jQuery<span class="level-label">Expert</span></h3>
                    <div class="level-bar">
                        <div class="level-bar-inner" data-level="96%">
                        </div>                                      
                    </div><!--//level-bar-->                                 
                </div><!--//item-->
                
                <div class="item">
                    <h3 class="level-title">HTML5, CSS3, SASS &amp; LESS<span class="level-label">Expert</span></h3>
                    <div class="level-bar">
                        <div class="level-bar-inner" data-level="96%">
                        </div>                                      
                    </div><!--//level-bar-->                                 
                </div><!--//item-->
                
                <div class="item">
                    <h3 class="level-title">Ruby on Rails<span class="level-label">Pro</span></h3>
                    <div class="level-bar">
                        <div class="level-bar-inner" data-level="85%">
                        </div>                                      
                    </div><!--//level-bar-->                                 
                </div><!--//item-->
                
                <p><a class="more-link" href="#"><i class="fa fa-external-link"></i> More on Coderwall</a></p> 
            </div>              
        </div><!--//content-->  
    </div><!--//section-inner-->                 
</aside>

blog/templates/blocks/widget/widget3.html
<aside class="testimonials aside section">
    <div class="section-inner">
        <h2 class="heading">Testimonials</h2>
        <div class="content">
            <div class="item">
                <blockquote class="quote">                                  
                    <p><i class="fa fa-quote-left"></i>James is an excellent software engineer and he is passionate about what he does. You can totally count on him to deliver your projects!</p>
                </blockquote>                
                <p class="source"><span class="name">Tim Adams</span><br /><span class="title">Curabitur commodo</span></p>                                                             
            </div><!--//item-->
            
            <p><a class="more-link" href="#"><i class="fa fa-external-link"></i> More on Linkedin</a></p> 
            
        </div><!--//content-->
    </div><!--//section-inner-->
</aside>

blog/templates/blocks/widget/widget4.html
<aside class="education aside section">
    <div class="section-inner">
        <h2 class="heading">Education</h2>
        <div class="content">
            <div class="item">                      
                <h3 class="title"><i class="fa fa-graduation-cap"></i> MSc Psychology and Computer Science</h3>
                <h4 class="university">University College London <span class="year">(2011-2012)</span></h4>
            </div><!--//item-->
            <div class="item">
                <h3 class="title"><i class="fa fa-graduation-cap"></i> BSc Computer Science</h3>
                <h4 class="university">University of Bristol <span class="year">(2008-2011)</span></h4>
            </div><!--//item-->
        </div><!--//content-->
    </div><!--//section-inner-->
</aside>

blog/templates/blocks/widget/widget5.html
<aside class="languages aside section">
    <div class="section-inner">
        <h2 class="heading">Languages</h2>
        <div class="content">
            <ul class="list-unstyled">
                <li class="item">
                    <span class="title"><strong>English:</strong></span>
                    <span class="level">Native Speaker <br class="visible-xs"/><i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> </span>
                </li><!--//item-->
                <li class="item">
                    <span class="title"><strong>Spanish:</strong></span>
                    <span class="level">Professional Proficiency <br class="visible-sm visible-xs"/><i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star-half"></i></span>
                </li><!--//item-->
            </ul>
        </div><!--//content-->
    </div><!--//section-inner-->
</aside>

blog/templates/blocks/widget/widget6.html
<aside class="blog aside section">
    <div class="section-inner">
        <h2 class="heading">Introduce  Admin</h2>
        <div id="rss-feeds" class="content">
        <img class="profile-image img-responsive pull-center center-block" src="https://scontent.fsgn4-1.fna.fbcdn.net/v/t1.0-1/p160x160/26994240_1763069480668467_3508211138446787995_n.jpg?_nc_cat=0&oh=9db8c44016a5b570dd9d71fb24d17213&oe=5B6FCF43" alt="dsf>" />
        <div class="profile-content pull-center">
            <h1 class="name text-center">Peter Dinh</h1>
            <h4 class="desc text-center">Developer Blog</h4>   
            <ul class="social list-inline center">
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>                   
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>               
                <li class="last-item"><a href="#"><i class="fa fa-hacker-news"></i></a></li>                 
            </ul> 
        </div><!--//profile-->
        </div><!--//content-->
    </div><!--//section-inner-->
</aside><!--//section-->

blog/templates/blocks/widget/widget7.html
<aside class="list music aside section">
    <div class="section-inner">
        <h2 class="heading">Catalog</h2>
        <div class="content">
            <ul class="list-unstyled">
                {% for item in list_catalog %}
                <li><i class="fa fa-tags"></i> <a href="{% url 'blog:catalog' item.id %}">{{ item.name }}</a></li>
                {% endfor %}
            </ul>
        </div><!--//content-->
    </div><!--//section-inner-->
</aside>

blog/templates/blocks/widget/widget8.html
<aside class="list conferences aside section">
    <div class="section-inner">
        <h2 class="heading">Conferences</h2>
        <div class="content">
            <ul class="list-unstyled">
                <li><i class="fa fa-calendar"></i> <a href="https://developer.apple.com/wwdc/" target="_blank">WWDC 2014</a> (San Francisco)</li>
                <li><i class="fa fa-calendar"></i> <a href="http://hive.aigaseattle.org/">Hive</a> (Seattle)</li>
            </ul>
        </div><!--//content-->
    </div><!--//section-inner-->
</aside>

blog/templates/blocks/widget/widget9.html
<aside class="credits aside section">
    <div class="section-inner">
        <h2 class="heading">Credits</h2>
        <div class="content">
            <ul class="list-unstyled">
                <li><a href="http://getbootstrap.com/" target="_blank"><i class="fa fa-external-link"></i> Bootstrap</a></li>
                <li><a href="http://fortawesome.github.io/Font-Awesome/" target="_blank"><i class="fa fa-external-link"></i> FontAwesome</a></li>
                <li><a href="http://jquery.com/" target="_blank"><i class="fa fa-external-link"></i> jQuery</a></li>
                <li><a href="https://github.com/IonicaBizau/github-calendar" target="_blank"><i class="fa fa-external-link"></i> GitHub Calendar Plugin</a></li>

                <li><a href="http://caseyscarborough.com/projects/github-activity/" target="_blank"><i class="fa fa-external-link"></i> GitHub Activity Stream</a></li>

                <li><a href="https://github.com/sdepold/jquery-rss" target="_blank"><i class="fa fa-external-link"></i> jQuery RSS</a></li>

                <li>Profile image: <a href="https://www.flickr.com/photos/dotbenjamin/2577394151" target="_blank">Ben Smith</a></li>
                <li>iPad and iPhone mocks: <a href="https://dribbble.com/perlerar" target="_blank">Regy Perlera</a></li>

            </ul>

            <hr/>

             <p>This responsive portfolio template is handcrafted by UX designer <a href="https://www.linkedin.com/in/xiaoying" target="_blank">Xiaoying Riley</a> at <a href="http://themes.3rdwavemedia.com/" target="_blank">3rd Wave Media</a> for developers and is <strong>FREE</strong> under the <a class="dotted-link" href="http://creativecommons.org/licenses/by/3.0/" target="_blank">Creative Commons Attribution 3.0 License</a></p>
             <p>We will improve or add new features to this template based on users' feedback so follow us on twitter to get notified when a new version is out!</p>
            <a class="btn btn-cta-secondary btn-follow" href="https://twitter.com/3rdwave_themes" target="_blank"><i class="fa fa-twitter"></i> Follow us</a>
            <a class="btn btn-cta-primary btn-download" href="http://themes.3rdwavemedia.com/website-templates/free-responsive-website-template-for-developers/" target="_blank"><i class="fa fa-download"></i> I want to download</a>
        </div><!--//content-->
    </div><!--//section-inner-->
</aside>